app:
  name: travel-tips-frontend
  namespace: sskd
  replicas: 1
  port: 3000
  healthPath: /

  image:
    repository: ghcr.io/etozhealkhipce/travel-tips
    tag: latest
    pullPolicy: Always

  imagePullSecrets:
    - name: travel-tips-frontend-ghcr-secret

  env:
    NODE_ENV: production
    SERVER_PORT: "3000"
    # API URL через публичный ingress бэкенда
    VITE_API_URL: https://travel-tips.sskd.tech/strapi

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

  # Ingress отключен - маршрутизация через backend ingress
  ingress:
    enabled: false
