app:
  name: travel-tips-frontend
  namespace: sskd
  replicas: 1
  port: 3000
  healthPath: /

  image:
    repository: ghcr.io/etozhealkhipce/travel-tips
    tag: latest
    pullPolicy: Always

  imagePullSecrets:
    - name: travel-tips-frontend-ghcr-secret

  env:
    NODE_ENV: production
    SERVER_PORT: "3000"
    VITE_API_URL: http://travel-tips-be:1337

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

  ingress:
    enabled: true
    host: travel-tips.sskd.tech
    path: /
    extraPaths:
      - path: /api
        pathType: Prefix
        serviceName: travel-tips-be
        servicePort: 1337
      - path: /admin
        pathType: Prefix
        serviceName: travel-tips-be
        servicePort: 1337
      - path: /uploads
        pathType: Prefix
        serviceName: travel-tips-be
        servicePort: 1337
